### ISSUE TITLE
Compiler error with 1.07 (but not with 1.03)

### ISSUE THREAD

**Issue by ClaesClaes** [SimpleHacks/QDEC#5]
Hi,
Just updated to 1.07 but get this compiler error: "call of overloaded 'QDecoder(int, int, bool)' is ambiguous".
I don't get this error with v 1.03
What could be the problem?

**Comment by fsievers** [comment]
@henrygab can you take a look at my pull request #6 that fixes the problem described here for me.

**Comment by henrygab** [comment]
@ClaesClaes -- Thanks for reporting this.
@fsievers -- Thanks for the PR.  I've accepted it, and will push a new version of the library shortly.
