### ISSUE TITLE
GPIO output gpio_num error on pure INPUT pins on ESP32

### ISSUE THREAD

**Issue by ScruffR** [SimpleHacks/QDEC#66]
On ESP32 devices there are several pins that are INPUT only and for these QDecoder::begin() causes an `GPIO output gpio_num error` at the attempt to turn on the pull-up resistor in legacy Arduino style.

```cpp
            pinMode(_pinA, INPUT_PULLUP);
            digitalWrite(_pinA, HIGH); // turn on pullup resistor
            pinMode(_pinB, INPUT_PULLUP);
            digitalWrite(_pinB, HIGH); // turn on pullup resistor
```

Since `pinMode(pin, PULLUP)` should already do the job, the `digitalWrite()` calls - which cause the error - can be omitted (or wrapped in conditional compile clauses).

**Comment by henrygab** [comment]
Thanks for opening this issue.  You're right that, for newer versions of Arduino, the digitalWrite is not required.

There was a reason that code was included.   I'm hesitant to remove it entirely.  Two follow-up questions for you:

1. Do you know if there is a way to detect when a GPIO is input-only in Arduino?
2. Do you have any recommended "safe" conditions that would exclude these?
    (e.g., how to detect an Arduino version in which it is no longer necessary?)

**Comment by ScruffR** [comment]
You could add this (general) check to support both versions
```cpp
#if defined(ARDUINO) && ARDUINO >= 101
  pinMode(pin, INPUT_PULLUP);
#else
  pinMode(pin, INPUT);
  digitalWrite(pin, HIGH); // Enable pull-up
#endif
```

Alternatively (but not tested) you could check whether `INPUT_PULLUP` is defined at all. 
If it is, there is pretty definetly no need for the legacy way of engaging the pull-up resistor.

**Comment by henrygab** [comment]
Looks good.  If you'd like to submit a PR with the above, I'd be happy to merge it.  Else, I will update in near future.
